### ISSUE TITLE
timetz not working as expected

### ISSUE THREAD

**Issue by podj** [python/tzdata#71]
It seems that whenever using both `timetz()` function and `ZoneInfo`, we are losing the UTC offset:
```python
from zoneinfo import ZoneInfo
from datetime import datetime, timezone

a = datetime.now().replace(tzinfo=ZoneInfo("America/Los_Angeles"))
print(a.timetz().isoformat()) # prints 14:11:41.516956

b = datetime.now().replace(tzinfo=timezone.utc)
print(b.timetz().isoformat())  # prints 14:11:41.518325+00:00
```

Or another example:
```python
from zoneinfo import ZoneInfo
from datetime import datetime, timezone

a = datetime.now().replace(tzinfo=ZoneInfo("America/Los_Angeles")).timetz()
print(a.utcoffset())  # prints 'None'
```

It seems that we are losing the timezone data whenever calling `timetz`.

I tested this snippets on both my personal Mac and remote machine running ubuntu:
Running on MacOS: Python 3.11.5, CPU Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz x86_64
Running on Ubuntu: Python 3.10.12 Apple M1 Pro 13.5.1 (22G90) Ventura

**Comment by pganssle** [comment]
This is not an issue with `tzdata`, if anything it would be an issue with CPython itself (the `zoneinfo` module). `tzdata` is a re-packaging of time zone *data* for PyPI.

That said, this is also expected behavior. `time` objects pretty much only support fixed offsets, because there's  no way for `ZoneInfo` to know what time zone to apply if you *only* give it the time of day. See [the documentation for `datetime.tzinfo`](https://docs.python.org/3/library/datetime.html#datetime.tzinfo.utcoffset).

To be honest, I'm not a big fan of `time` having support for offsets in the first place. I can't think of a good use case for it.

**Comment by podj** [comment]
@pganssle thank you so much for your answer!
